//LOG IN TYPE OF ACTION 
export const LOG_IN = "LOG_IN";

//LOG OUT TYPE OF ACTION
export const LOG_OUT = "LOG_OUT";

//SAVE USERNAME TYPE OF ACTION
export const SAVE_USER = "SAVE_USER";

//INITIATE NEW ROUND TYPE OF ACTION
export const START_NEW_ROUND="START_NEW_ROUND";

//INITIATE HIDE CARDS TYPE OF ACTION
export const HIDE_CARDS = "HIDE_CARDS";

//INITIATE REVEAL CARD TYPE OF ACTION
export const REVEAL_CARD = "REVEAL_CARD";

//INITIATE FORFEIT TYPE OF ACTION
export const FORFEIT = "FORFEIT";
