//LOG IN TYPE OF ACTION 
export const LOG_IN = "LOG_IN";

//LOG OUT TYPE OF ACTION
export const LOG_OUT = "LOG_OUT";

//SAVE USERNAME TYPE OF ACTION
export const SAVE_USER = "SAVE_USER";

//INITIATE NEW ROUND TYPE OF ACTION
export const START_NEW_ROUND="START_NEW_ROUND";

//TYPE OF ACTION WHEN PAGE IS REFRESHED
export const REFRESH_PAGE = "REFRESH_PAGE";
